@extends('errors.layout')
@section('code', '401')
@section('title', 'Unauthorized')
@section('icon', '🔒')
@section('heading', 'Unauthorized Access')
@section('message', 'You must be logged in to view this page. Please sign in and try again.')
