@extends('errors.layout')
@section('code', '404')
@section('title', 'Page Not Found')
@section('icon', '🔍')
@section('heading', 'Page Not Found')
@section('message', 'Sorry, we couldn\'t find the page you\'re looking for. It may have been moved or deleted.')
