@extends('errors.layout')
@section('code', '429')
@section('title', 'Too Many Requests')
@section('icon', '🛑')
@section('heading', 'Slow Down!')
@section('message', 'You\'ve made too many requests in a short period. Please wait a moment and try again.')
