@extends('errors.layout')
@section('code', '500')
@section('title', 'Server Error')
@section('icon', '💥')
@section('heading', 'Internal Server Error')
@section('message', 'Something went wrong on our end. Our team has been notified. Please try again in a few moments.')
