<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('hotspot_purchase_requests', function (Blueprint $table) {
            $table->id();

            // Exact MikroTik router serving the captive portal customer.
            $table->string('router_name');

            // Customer identity supplied by the MikroTik captive portal.
            $table->string('mac_address', 64);
            $table->string('ip_address', 64)->nullable();

            // Requested package.
            $table->foreignId('package_id')
                ->nullable()
                ->constrained('package_lists')
                ->nullOnDelete();

            $table->string('package_name');
            $table->decimal('amount', 14, 2);
            $table->char('currency', 3)->default('TZS');

            // Customer payment details.
            $table->string('phone', 32);
            $table->string('payment_gateway', 50)->nullable();

            // Unique request/reference generated by our server.
            $table->string('merchant_reference')->unique();

            // Existing provider/payment transaction, when available.
            $table->foreignId('payment_transaction_id')
                ->nullable()
                ->constrained('payment_transactions')
                ->nullOnDelete();

            // Payment state is deliberately separate from activation state.
            $table->string('payment_status', 30)->default('pending');
            $table->timestamp('paid_at')->nullable();

            // Activation state.
            $table->string('activation_status', 30)->default('pending');
            $table->timestamp('activation_started_at')->nullable();
            $table->timestamp('activated_at')->nullable();
            $table->timestamp('activation_failed_at')->nullable();

            // Router/captive-portal information useful for troubleshooting.
            $table->string('login_url', 1000)->nullable();
            $table->string('link_login', 1000)->nullable();
            $table->string('original_destination', 2000)->nullable();

            // Generated Hotspot credentials after activation.
            $table->string('hotspot_username')->nullable();
            $table->string('hotspot_password')->nullable();

            // Error/status information.
            $table->text('activation_error')->nullable();
            $table->text('notes')->nullable();

            $table->timestamps();

            $table->index(['router_name', 'mac_address']);
            $table->index(['router_name', 'activation_status']);
            $table->index(['payment_status', 'activation_status']);
            $table->index('phone');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('hotspot_purchase_requests');
    }
};
